version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - python3 --version  # Check the Python version
      - pip3 --version  # Check pip version
      - pip3 install --upgrade pip  # Ensure pip is up-to-date
      - pip3 install -r requirements.txt  # Install dependencies from requirements.txt
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Post-build phase completed"

artifacts:
  files:
    - '**/*'  # Ensure all files are included
